{
  rules: {
    # value 0 indicates rule DISABLED
    'force-element-nesting': 0,       # permit div h1 {..} instead of div { h1 {..} }
    'mixins-before-declarations': 0,  # ignore ordering of mixins relative to rules
    'nesting-depth': 0,               # allow max nesting depth (prefer < 4)
    'no-important': 0,                # ignore !important (needed in some places)
    'property-sort-order': 0,         # ignore alphabetical order for properties
    'force-pseudo-nesting': 0,        # permit .cls:hover {..} over .cls { &:hover { .. }}
    'no-color-literals': 0,           # allow use of rgba(..) in rules (not just vars)
    'placeholder-in-extend': 0,       # allow @extend statements to call normal classes
    'no-ids': 0                       # allow IDs to be used as selectors (_avoid_)
  }
}
