var _this=this;console.log('hello'),$(document).ready(()=>{$('.carousel.slide').carousel({interval:!1}).carousel('pause').on('swipeleft',()=>{$(_this).carousel('next')}).on('swiperight',()=>{$(_this).carousel('prev')}).on('movestart',function(a){(a.distX>a.distY&&a.distX<-a.distY||a.distX<a.distY&&a.distX>-a.distY)&&a.preventDefault()})}),$(()=>{const a=$('.gallery.module'),b=a.find('.full-image .gallery-image img');a.on('click','.slides .gallery-image',function(c){c.preventDefault();const d=$(this),f=d.find('.thumbnail img').attr('src'),g=d.find('.gallery-caption').html();return console.log(d.find('.gallery-image img').length),b.fadeOut(100,()=>{b.attr('src',f)}).fadeIn(100),g.html(g),!0})}),$(()=>{const a=$('.switcher');a.on('click',()=>{a.toggleClass('on'),a.toggleClass('two-column')})}),function(a,b,c){'object'==typeof module&&module&&'object'==typeof module.exports?module.exports=c:(a[b]=c,'function'==typeof define&&define.amd&&define(b,[],()=>{return c}))}(this,'jRespond',function(a,b,c){// eslint-disable-line no-shadow-restricted-names
return function(d){// array for registered functions
const f=[],g=[],l=d;// array that corresponds to mediaListeners and holds the current on/off state
// array of media query breakpoints; adjust as needed
// store the current breakpoint
let m='',n='',o=0;// the previous breakpoint
// window resize event timer stuff
// let resizeTimer;
const p=500;let q=p;// cross browser window width
const r=()=>{let z=0;// IE
return z='number'==typeof window.innerWidth?window.innerWidth:0===document.documentElement.clientWidth?document.body.clientWidth:document.documentElement.clientWidth,z},s=function(z){// if there's an array of breakpoints
if('object'!=typeof z){if('*'===z)return!0;// or if it's a single breakpoint
if('string'==typeof z&&m===z)return!0}else if(0<=z.join().indexOf(m))return!0;// if the string is '*' then run at every breakpoint
return!1},t=function(z){const A=z.breakpoint,B=z.enter||c;f.push(z),g.push(!1),s(A)&&(B!==c&&B.call(null,{entering:m,exiting:n}),g[f.length-1]=!0)},u=function(z){if(z.length===c)t(z);else for(let A=0;A<z.length;A++)t(z[A])},v=()=>{const z=[],A=[];for(let C=0;C<f.length;C++){const D=f[C].breakpoint,E=f[C].enter||c,F=f[C].exit||c;'*'===D?(E!==c&&z.push(E),F!==c&&A.push(F)):s(D)?(E!==c&&!g[C]&&z.push(E),g[C]=!0):(F!==c&&g[C]&&A.push(F),g[C]=!1)}const B={entering:m,exiting:n};// loop through exit functions to call
for(let C=0;C<A.length;C++)A[C].call(null,B);// then loop through enter functions to call
for(let C=0;C<z.length;C++)z[C].call(null,B)},x=function(z){let B,A=!1;// look for existing breakpoint based on width
// since this is used outside of the loop we want to give it greater scope
for(B=0;B<l.length;B++)// if registered breakpoint found, break out of loop
if(z>=l[B].enter&&z<=l[B].exit){A=!0;break}// if breakpoint is found and it's not the current one
A&&m!==l[B].label?(n=m,m=l[B].label,v()):!A&&''!=m&&(m='',v())},y=()=>{// get current width
const z=r();// if there is a change speed up the timer and fire the returnBreakpoint function
z===o?q=p:(q=100,x(z)),o=z,setTimeout(y,q)};// takes the breakpoint/s arguement from an object and tests it against the current state
// send media to the mediaListeners array
// determine input type
// loops through all registered functions and determines what should be fired
// checks for the correct breakpoint against the mediaBreakpoints list
// self-calling function that checks the browser width and delegates if it detects a change
// return
return y(),{addFunc(z){u(z)},getBreakpoint(){return m}}}}(this,this.document)),$(document).ready(()=>{const a=$('header.site-header'),b=a.find('li.slide-menu'),c=a.find('.gateway-navigation'),d=a.find('.main-navigation'),f=$('body'),g=$(window),l=d.offset(),m=jRespond([// eslint-disable-line no-undef
{label:'mobile',enter:0,exit:767},{label:'tablet',enter:768,exit:991},{label:'laptop',enter:992,exit:1199},{label:'desktop',enter:1200,exit:10000}]),n=()=>{f.wrapInner('<div id="js-mobile-content-wrapper"></div>'),$('[data-toggle="offcanvas"]').on('click.mobile',()=>{const u=$(_this),v=$(u.data('target')),x=v.hasClass('offcanvas-left')?'active-left':// eslint-disable-line no-nested-ternary
!!v.hasClass('offcanvas-right')&&'active-right';x&&f.toggleClass(x)})},o=()=>{$('[data-toggle="offcanvas"]').off('.mobile').off('.mobileclose'),$('body').removeClass('active-left').removeClass('active-right'),$('#js-mobile-content-wrapper>:first-child').unwrap()};// Offcanvas menus for mobile
// Add slidedown/slideup animations to header dropdowns using Bootstrap's events:
$('#scu-main-navigation+nav .scu-nav').hover(()=>{f.toggleClass('nav-dropdown-open')});const p=()=>{let u,v;// Pages that do not have a site header will break unless we check here
a.length?(u=c.offset().top-$(document).scrollTop(),v=l.top>c.outerHeight()+u-1?l.top-c.outerHeight()-u-1:c.outerHeight()+u-1):v=0,d.data('bs.affix')?d.data('bs.affix').options.offset.top=v:d.affix({offset:{top:v}})},q=function(u){u.preventDefault();const v=$(this).parents('li.slide-menu'),x=v.find('div.slide-panel'),y=d.hasClass('affix')?c.add(d):c;let z=x.outerHeight();if(v.hasClass('open'))x.find('.row').fadeOut(()=>{x.hide().find('.row').show()}),y.stop().animate({top:`-=${z}`},{complete(){v.removeClass('open'),p(),d.hasClass('affix')||d.css('top','')},step(A){/*
           If ($this is $mainNav) and (now - $(window).scrollTop() <=
           $mainNav's default position ) then
           */const B=$(this);B.hasClass('affix')&&B.hasClass('main-navigation')&&A+$(window).scrollTop()<=l.top&&B.removeClass('affix').addClass('affix-top')}});else{// Opening or switching here
const A=b.not(v).filter('.open').removeClass('open').find('div.slide-panel');A.length&&(z-=A.outerHeight()),y.stop().animate({top:`+=${z}`},{complete(){p(),d.hasClass('affix')||d.css('top',`${c.outerHeight()+c.offset().top-$(document).scrollTop()-1}px`)},step(B){const C=$(this);/*
           If $animated does not contain $mainNav, and $this = $gatewayNav, and
           $gatewayNav's bottome edge is past the main nav's top offset, convert
           main nav to affix and animate its top:
           */!y.filter('.main-navigation').length&&C.hasClass('gateway-navigation')&&B+c.outerHeight()-1>=l.top-$(window).scrollTop()?d.removeClass('affix-top').addClass('affix').css('top',B+c.outerHeight()-1):C.hasClass('affix')&&C.hasClass('main-navigation')&&B+$(window).scrollTop()<=l.top&&C.removeClass('affix').addClass('affix-top')}}),A.fadeOut(),v.addClass('open'),x.fadeIn()}},r=()=>{b.on('click.tabletUp','a[role="button"]',q)},s=()=>{b.off('.tabletUp')},t=()=>{p(),b.filter('.open').length&&b.filter('.open').each(()=>{const u=$(_this),v=u.find('div.slide-panel').outerHeight();u.parents('.gateway-navigation').css('top',`${v}px`),d.hasClass('affix')&&d.css('top',`${v-1+c.outerHeight()}px`)})};// Slide menus for tablet/desktop drawers in gateway navigation
// Hook up init functions with breakpoints:
mediaCheck({// eslint-disable-line no-undef
media:'(max-width: 767px)',// Mobile only
entry:()=>{s(),n()},exit:()=>{o(),r(),setTimeout(()=>{p()},250)}}),mediaCheck({// eslint-disable-line no-undef
media:'(min-width: 1065px) and (max-width: 1199px)',entry:t,exit:t}),function(){function v(){768<=g.width()||(D=1,A.width(0.5*g.width()),C=A.outerWidth(),z.css('left',f.width()-C-B-25))}function x(){D>=A.length||(z.animate({left:z.position().left-C-B},300),D++)}function y(){1==D||(z.animate({left:z.position().left+C+B},300),D--)}const z=$('.can-we-boxes'),A=z.find('.can-we-box'),B=30;let C,D;m.addFunc({breakpoint:'mobile',enter:()=>{v(),A.on('swipeleft',x).on('swiperight',y),g.on('resize',v)},exit:()=>{g.off('resize',v),A.off('swipeleft').off('swiperight'),A.css('width','auto'),z.css('left','auto')}})}()}),function(a){// ENTER CLASS DEFINITION
// ======================
// const dataApi = '[data-grid="images"]';
const b=function(d,f){this.cleanWhitespace(d),this.row=0,this.rownum=1,this.elements=[],this.element=d,this.albumWidth=a(d).width(),this.images=a(d).children(),this.options=a.extend({},b.DEFAULTS,f),a(window).on('resize',a.proxy(this.handleResize,this)),this.processImages()};b.VERSION='3.3.1',b.TRANSITION_DURATION=350,b.DEFAULTS={padding:10,targetHeight:300,display:'inline-block'},b.prototype.handleResize=()=>{this.row=0,this.rownum=1,this.elements=[],this.albumWidth=a(this.element).width(),this.images=a(this.element).children(),this.processImages()},b.prototype.processImages=()=>{const d=this;this.images.each(function(f){const g=a(this),l=g.is('img')?g:g.find('img'),m='undefined'==typeof l.data('width')?l.width():l.data('width'),n='undefined'==typeof l.data('height')?l.height():l.data('height');l.data('width',m),l.data('height',n);const o=Math.ceil(m/n*d.options.targetHeight),p=Math.ceil(d.options.targetHeight);d.elements.push([this,o,p]),d.row+=o+d.options.padding,d.row>d.albumWidth&&d.elements.length&&(d.resizeRow(d.row-d.options.padding),d.row=0,d.elements=[],d.rownum+=1),d.images.length-1===f&&d.elements.length&&(d.resizeRow(d.row),d.row=0,d.elements=[],d.rownum+=1)})},b.prototype.resizeRow=function(d){// const that = this;
const f=this.options.padding*(this.elements.length-1),g=this.albumWidth-f,l=g/(d-f);let m=f;// const lastRow = row < this.albumWidth;
for(let n=0;n<this.elements.length;n++){const o=a(this.elements[n][0]);let p=Math.floor(this.elements[n][1]*l);const q=Math.floor(this.elements[n][2]*l),r=n<this.elements.length-1;m+=p,!r&&m<this.albumWidth&&(p+=this.albumWidth-m),p--;const s=o.is('img')?o:o.find('img');s.width(p),s.height(q),this.applyModifications(o,r)}},b.prototype.applyModifications=function(d,f){const g={'margin-bottom':`${this.options.padding}px`,'margin-right':f?`${this.options.padding}px`:0,display:this.options.display,'vertical-align':'bottom'};d.css(g)},b.prototype.cleanWhitespace=function(d){a(d).contents().filter(()=>{return 3===this.nodeType&&!/\S/.test(this.nodeValue)}).remove()};const c=a.fn.imageGrid;a.fn.imageGrid=// IMAGE GRID PLUGIN DEFINITION
// ============================
function(f){return this.each(()=>{const g=a(this);let l=g.data('bs.image-grid');const m=a.extend({},b.DEFAULTS,g.data(),'object'==typeof f&&f);l||g.data('bs.image-grid',l=new b(this,m)),'string'==typeof f&&l[f].call(g)})},a.fn.imageGrid.Constructor=b,a.fn.imageGrid.noConflict=()=>{return a.fn.imageGrid=c,this},a(()=>{a('[data-grid="images"]').imageGrid()})}(jQuery),function(a){const b=function(d,f){this.element=d,this.options=f};// STAGE CLASS DEFINITION
// ======================
b.VERSION='3.3.5',b.TRANSITION_DURATION=150,b.DEFAULTS={easing:'cubic-bezier(.2,.7,.5,1)',duration:300,delay:0,distance:250,hiddenElements:'#sidebar'},b.prototype.isOpen=()=>{return a(this.element).hasClass('stage-open')},b.prototype.toggle=()=>{this.isOpen()?this.close():this.open()},b.prototype.open=()=>{const d=this;return a(document.body).css('overflow','hidden'),'ontouchstart'in document.documentElement&&a(document).on('touchmove.bs.stage',function(f){f.preventDefault()}),a(this.options.hiddenElements).removeClass('hidden'),a(window).one('keydown.bs.stage',a.proxy(function(f){27===f.which&&this.close()},this)),a(this.element).on('click.bs.stage',a.proxy(this.close,this)).trigger('open.bs.stage').addClass('stage-open'),a.support.transition?void(a(this.element).css({'-webkit-transition':`-webkit-transform ${this.options.duration}ms ${this.options.easing}`,'-ms-transition':`-ms-transform ${this.options.duration}ms ${this.options.easing}`,transition:`transform ${this.options.duration}ms ${this.options.easing}`}),this.element.offsetWidth,a(this.element).css({'-webkit-transform':`translateX(${this.options.distance}px)`,'-ms-transform':`translateX(${this.options.distance}'px)`,transform:`translateX(${this.options.distance}px)`}).one('bsTransitionEnd',()=>{a(d.element).trigger('opened.bs.stage')}).emulateTransitionEnd(this.options.duration)):void a(d.element).css({left:`${this.options.distance}px`,position:'relative'}).trigger('opened.bs.stage')},b.prototype.close=()=>{function d(){a(document.body).css('overflow','auto'),'ontouchstart'in document.documentElement&&a(document).off('touchmove.bs.stage'),a(f.options.hiddenElements).addClass('hidden'),a(f.element).removeClass('stage-open').css({'-webkit-transition':'','-ms-transition':'',transition:''}).css({'-webkit-transform':'','-ms-transform':'',transform:''}).trigger('closed.bs.stage')}a(window).off('keydown.bs.stage');const f=this;return a.support.transition?void a(this.element).trigger('close.bs.stage').off('click.bs.stage').css({'-webkit-transform':'none','-ms-transform':'none',transform:'none'}).one('bsTransitionEnd',d).emulateTransitionEnd(this.options.duration):(a(this.element).trigger('close.bs.stage').css({left:'',position:''}).off('click.bs.stage'),d())};const c=a.fn.stage;a.fn.stage=// STAGE PLUGIN DEFINITION
// =======================
function(f){return this.each(()=>{const g=a(this);let l=g.data('bs.stage');const m=a.extend({},b.DEFAULTS,g.data(),'object'==typeof f&&f);l||g.data('bs.stage',l=new b(this,m)),'string'==typeof f&&l[f]()})},a.fn.stage.Constructor=b,a.fn.stage.noConflict=()=>{return a.fn.stage=c,this},a(document).on('click','[data-toggle="stage"]',()=>{const d=a(this).data(),f=a(this.getAttribute('data-target'));f.data('bs.stage')||f.stage(d),f.stage('toggle')})}(jQuery),function(a){/**
   * The zoom object
   */function b(d){this._fullHeight=this._fullWidth=this._overlay=this._targetImageWrap=null,this._targetImage=d,this._$body=a(document.body)}/**
   * The zoom service
   */function c(){this._activeZoom=this._initialScrollPosition=this._initialTouchPosition=this._touchMoveListener=null,this._$document=a(document),this._$window=a(window),this._$body=a(document.body),this._boundClick=a.proxy(this._clickHandler,this)}c.prototype.listen=()=>{this._$body.on('click','[data-action="zoom"]',a.proxy(this._zoom,this))},c.prototype._zoom=function(d){const f=d.target;return f&&'IMG'===f.tagName?this._$body.hasClass('zoom-overlay-open')?void 0:d.metaKey||d.ctrlKey?window.open(d.target.getAttribute('data-original')||d.target.src,'_blank'):void(f.width>=a(window).width()-b.OFFSET||(this._activeZoomClose(!0),this._activeZoom=new b(f),this._activeZoom.zoomImage(),this._$window.on('scroll.zoom',a.proxy(this._scrollHandler,this)),this._$document.on('keyup.zoom',a.proxy(this._keyHandler,this)),this._$document.on('touchstart.zoom',a.proxy(this._touchStart,this)),document.addEventListener?document.addEventListener('click',this._boundClick,!0):document.attachEvent('onclick',this._boundClick,!0),'bubbles'in d?d.bubbles&&d.stopPropagation():d.cancelBubble=!0)):void 0},c.prototype._activeZoomClose=function(d){this._activeZoom&&(d?this._activeZoom.dispose():this._activeZoom.close(),this._$window.off('.zoom'),this._$document.off('.zoom'),document.removeEventListener('click',this._boundClick,!0),this._activeZoom=null)},c.prototype._scrollHandler=()=>{null===this._initialScrollPosition&&(this._initialScrollPosition=a(window).scrollTop());const d=this._initialScrollPosition-a(window).scrollTop();40<=Math.abs(d)&&this._activeZoomClose()},c.prototype._keyHandler=function(d){27===d.keyCode&&this._activeZoomClose()},c.prototype._clickHandler=function(d){d.preventDefault?d.preventDefault():event.returnValue=!1,'bubbles'in d?d.bubbles&&d.stopPropagation():d.cancelBubble=!0,this._activeZoomClose()},c.prototype._touchStart=function(d){this._initialTouchPosition=d.touches[0].pageY,a(d.target).on('touchmove.zoom',a.proxy(this._touchMove,this))},c.prototype._touchMove=function(d){10<Math.abs(d.touches[0].pageY-this._initialTouchPosition)&&(this._activeZoomClose(),a(d.target).off('touchmove.zoom'))},b.OFFSET=80,b._MAX_WIDTH=2560,b._MAX_HEIGHT=4096,b.prototype.zoomImage=()=>{const d=document.createElement('img');d.onload=a.proxy(()=>{this._fullHeight=+d.height,this._fullWidth=+d.width,this._zoomOriginal()},this),d.src=this._targetImage.src},b.prototype._zoomOriginal=()=>{this._targetImageWrap=document.createElement('div'),this._targetImageWrap.className='zoom-img-wrap',this._targetImage.parentNode.insertBefore(this._targetImageWrap,this._targetImage),this._targetImageWrap.appendChild(this._targetImage),a(this._targetImage).addClass('zoom-img').attr('data-action','zoom-out'),this._overlay=document.createElement('div'),this._overlay.className='zoom-overlay',document.body.appendChild(this._overlay),this._calculateZoom(),this._triggerAnimation()},b.prototype._calculateZoom=()=>{this._targetImage.offsetWidth;// eslint-disable-line no-unused-expressions
const d=this._fullWidth,f=this._fullHeight,g=d/this._targetImage.width,l=a(window).height()-b.OFFSET,m=a(window).width()-b.OFFSET;// const scrollTop = $(window).scrollTop();
this._imgScaleFactor=d<m&&f<l?g:d/f<m/l?l/f*g:m/d*g},b.prototype._triggerAnimation=()=>{this._targetImage.offsetWidth;// eslint-disable-line no-unused-expressions
const d=a(this._targetImage).offset(),f=a(window).scrollTop(),g=f+a(window).height()/2,l=a(window).width()/2,m=d.top+this._targetImage.height/2,n=d.left+this._targetImage.width/2;this._translateY=g-m,this._translateX=l-n;const o=`scale(${this._imgScaleFactor})`;let p=`translate(${this._translateX}px, ${this._translateY}px)`;a.support.transition&&(p+=' translateZ(0)'),a(this._targetImage).css({'-webkit-transform':o,'-ms-transform':o,transform:o}),a(this._targetImageWrap).css({'-webkit-transform':p,'-ms-transform':p,transform:p}),this._$body.addClass('zoom-overlay-open')},b.prototype.close=()=>{return this._$body.removeClass('zoom-overlay-open').addClass('zoom-overlay-transitioning'),a(this._targetImage).css({'-webkit-transform':'','-ms-transform':'',transform:''}),a(this._targetImageWrap).css({'-webkit-transform':'','-ms-transform':'',transform:''}),a.support.transition?void a(this._targetImage).one(a.support.transition.end,a.proxy(this.dispose,this)).emulateTransitionEnd(300):this.dispose()},b.prototype.dispose=()=>{this._targetImageWrap&&this._targetImageWrap.parentNode&&(a(this._targetImage).removeClass('zoom-img').attr('data-action','zoom'),this._targetImageWrap.parentNode.replaceChild(this._targetImage,this._targetImageWrap),this._overlay.parentNode.removeChild(this._overlay),this._$body.removeClass('zoom-overlay-transitioning'))},a(()=>{new c().listen()})}(jQuery),function(a){const b=function(d,f){a.support.transition&&(this.element=d,this.options=f,this.handler=null,this.addEventListeners())};// ENTER CLASS DEFINITION
// ======================
b.VERSION='3.3.5',b.DEFAULTS={easing:'cubic-bezier(.2,.7,.5,1)',duration:1200,delay:0},b.prototype.addEventListeners=()=>{const d=a.proxy(this.checkForEnter,this);// this.listener =
a(window).on('scroll.enter',this.handler=()=>{window.requestAnimationFrame(d)}),this.checkForEnter()},b.prototype.removeEventListeners=()=>{a(window).off('scroll.enter',this.handler)},b.prototype.checkForEnter=()=>{const d=window.innerHeight,f=this.element.getBoundingClientRect();0<=d-f.top&&setTimeout(a.proxy(this.triggerEntrance,this),this.options.delay)},b.prototype.triggerEntrance=()=>{this.removeEventListeners(),a(this.element).css({'-webkit-transition':`-webkit-transform ${this.options.duration}ms ${this.options.easing}`,'-ms-transition':`-ms-transform ${this.options.duration}ms ${this.options.easing}`,transition:`transform ${this.options.duration}ms ${this.options.easing}`}).css({'-webkit-transform':'none','-ms-transform':'none',transform:'none'}).trigger('enter.bs.enter')};const c=a.fn.enter;a.fn.enter=// ENTER PLUGIN DEFINITION
// =======================
function(f){return this.each(()=>{const g=a(this);let l=g.data('bs.enter');const m=a.extend({},b.DEFAULTS,g.data(),'object'==typeof f&&f);l||g.data('bs.enter',l=new b(this,m)),'string'==typeof f&&l[f]()})},a.fn.enter.Constructor=b,a.fn.enter.noConflict=()=>{return a.fn.enter=c,this},a(()=>{a('[data-transition="entrance"]').enter()})}(jQuery);